### ISSUE TITLE
install: verify reqirements for new version of fastapi[all]

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cc#9]
This has changed from last week, there may be a new version of fastapi out there that requires rust as implementation engine, so we need to check and add documentation to installing rust where needed

**Comment by laszewsk** [comment]
how do we do a conditional install fro 


linux
windows
osx

I think on osx [all] may not work ?

**Comment by jpfleischer** [comment]
```bash
cd ~/cm/cloudmesh-cc
pip install -e .
```
on fresh install macOS, this successfully installs fastapi[all]
so rust install is not necessary.

**Comment by laszewsk** [comment]
I thoink this is only on intel mac ok, m1 mac may be different

**Comment by jpfleischer** [comment]
it appears possible to run fastapi on m1 macs:
https://stackoverflow.com/questions/71566888/running-fastapi-app-in-anaconda3-on-m1-macbook
https://github.com/tiangolo/fastapi/issues/3250#issuecomment-1080033576
we just might need to mention in documentation that the architecture installation of python needs to be consistent.

i cant definitively solve this bug since i do not have mac with silicon, so i cant test anything. i only have mac on "intel" (which is actually running on my ryzen but simulates an intel)

**Comment by laszewsk** [comment]
we do not want anaconda.

The issue is that for M1 mac we need some other way to install it for now
I am not sure if we can put something in requirements.txt and setup.py that tests it and does the right thing. 
In general we just need a section:

Installation Changes for M1 Mac and document how to install

I however have done this already so I am not sure what the packages are that I changed
maybe if I have time I create new venv and try again
for now please leaf open till we can verify instalation on m1 mac also

**Comment by laszewsk** [comment]
ps: I had issues with fastapi[all] but need to retest

**Comment by laszewsk** [comment]
works under 3.7.10
